runtime: python38

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
  secure: always

- url: /static
  static_dir: static
  secure: always
  http_headers:
    Strict-Transport-Security: "max-age=2592000; includeSubdomains"

- url: /.*
  script: auto

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?.*/jspm_packages/.*$
# - ^(.*/)?\..*$
- ^(.*/)?.*\.scss$
- ^(.*/)?.*\.md$
